### PR TITLE
update deps for node 6 nan changes

### PR DESCRIPTION
**Pull request by ZECTBynmo**

### CODE REVIEW

**Comment by ZECTBynmo** [comment]
This addresses a build failure I was seeing on npm install. Just to leave google search breadcrumbs for other devs, here's the error: 

``````
(node:63472) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.

> microtime@2.0.0 install /Users/ZECTbynmo/Projects/qZeno/node_modules/microtime
> node-gyp rebuild

  CXX(target) Release/obj.target/microtime/src/microtime.o
In file included from ../src/microtime.cc:9:
../node_modules/nan/nan.h:590:20: error: no type named 'GCEpilogueCallback' in 'v8::Isolate'
      v8::Isolate::GCEpilogueCallback callback
      ~~~~~~~~~~~~~^
../node_modules/nan/nan.h:596:20: error: no type named 'GCEpilogueCallback' in 'v8::Isolate'
      v8::Isolate::GCEpilogueCallback callback) {
      ~~~~~~~~~~~~~^
../node_modules/nan/nan.h:601:20: error: no type named 'GCPrologueCallback' in 'v8::Isolate'
      v8::Isolate::GCPrologueCallback callback
      ~~~~~~~~~~~~~^
../node_modules/nan/nan.h:607:20: error: no type named 'GCPrologueCallback' in 'v8::Isolate'
      v8::Isolate::GCPrologueCallback callback) {
      ~~~~~~~~~~~~~^```
``````

**Comment by anvaka** [comment]
No worries about failing build - I'm using very old version of node in the CI. I bumped it to later version of node to see how it goes.

**Comment by anvaka** [comment]
Thank you for the PR!

**Comment by anvaka** [comment]
Fixed travis config, so the build is green now.

I still have failing tests in zuul. Please let me know if you run into any problems in the browser.

**Pull request merged**
